<DevSupportScreenView>:

    CStackLayout:
        size_hint: 1, 1
        spacing: dp(16)
        padding: dp(16)

        ActiveButton:
            icon: "arrow--left"
            on_press:
                app.manager_screens.current = "entrypoint screen"

        ElasticScrollView:

            CGridLayout:
                spacing: dp(16)
                adaptive: [False, True]
                padding: [0, 0, 0, dp(256)]
                cols: 1

                RoundedBoxLayout:
                    adaptive: [False, True]
                    spacing: dp(20)
                    bg_color: app.layer_01
                    orientation: "vertical"
                    padding: [dp(16)]
                    radius: dp(16)

                    AsyncImage:
                        source: "data/wise.png"
                        fit_mode: "cover"
                        size_hint: 1, None
                        height: self.width*9/16

                    CDivider:

                    CLabel:
                        text: "Support the development through WISE."

                    ActiveButtonInfo:
                        text: "Continue"
                        icon: "chevron--right"
                        pos_hint: {"right": 1.0}
                        on_press:
                            app.web_open("https://wise.com/pay/business/kartavyashukla")

                RoundedBoxLayout:
                    adaptive: [False, True]
                    spacing: dp(20)
                    bg_color: app.layer_01
                    orientation: "vertical"
                    padding: [dp(16)]
                    radius: dp(16)

                    AsyncImage:
                        source: "data/paypal.png"
                        fit_mode: "cover"
                        size_hint: 1, None
                        height: self.width*9/16

                    CDivider:

                    CLabel:
                        text: "Support the development through Paypal."

                    ActiveButtonInfo:
                        text: "Continue"
                        icon: "chevron--right"
                        pos_hint: {"right": 1.0}
                        on_press:
                            app.web_open("https://paypal.me/KARTAVYASHUKLA")

                RoundedBoxLayout:
                    adaptive: [False, True]
                    spacing: dp(20)
                    bg_color: app.layer_01
                    orientation: "vertical"
                    padding: [dp(16)]
                    radius: dp(16)

                    AsyncImage:
                        source: "data/githubsponsors.png"
                        fit_mode: "cover"
                        size_hint: 1, None
                        height: self.width*9/16

                    CDivider:

                    CLabel:
                        text: "Support the development through Github Sponsors."

                    ActiveButtonInfo:
                        text: "Continue"
                        icon: "chevron--right"
                        pos_hint: {"right": 1.0}
                        on_press:
                            app.web_open("https://github.com/sponsors/Novfensec")



