#: import FT kivy.uix.screenmanager.FadeTransition


<ActiveButton>:
    radius: self.height/2
    text_color: app.text_primary
    text_color_active: app.text_primary
    active_color: app.background_hover
    text_color_focus: app.text_primary


<ActiveButtonDark@ActiveButton>:
    bg_color: app.gray_100
    hover_color: app.gray_80
    active_color: app.gray_100
    -text_color: app.text_on_color
    -text_color_focus: [1, 1, 1, 1]


<ActiveButtonSuccess@ActiveButton>:
    bg_color: app.support_success
    active_color: app.support_success_inverse
    -text_color: app.text_inverse
    -text_color_focus: app.text_inverse


<ActiveButtonError@ActiveButton>:
    bg_color: app.support_error
    active_color: app.support_error_inverse
    -text_color: app.text_inverse
    -text_color_focus: app.text_inverse


<ActiveButtonInfo@ActiveButton>:
    bg_color: app.button_primary
    active_color: app.button_primary_active
    -text_color: app.text_on_color
    -text_color_focus: app.text_on_color

<MainScreen>:
    CStackLayout:
        size_hint: 1, 1
        spacing: dp(8)

        CBoxLayout:
            id: main_layout
            size_hint: 1, 1
            orientation: "vertical"


<CScreenManager>:
    transition: FT(duration=0.15, clearcolor=app.background)


<LoadingLayout>:

    size_hint: 1, 1

    CLoadingIndicator:
        role: "Small"


<BanLayout>:
    bg_color: app.background

    CBoxLayout:
        orientation: "vertical"
        adaptive: [False, True]
        size_hint_x: 1
        spacing: dp(32)

        CIcon:
            icon: "error--filled"
            font_size: sp(128)
            color: app.support_error
            pos_hint: {"center_x": 0.5}

        CLabel:
            text: f"An Unknown error occurred!\nPlease try after some time."
            style: "heading_03"
            halign: "center"

        CLink:
            pos_hint: {"center_x": 0.5}
            role: "Large"
            on_press:
                app.ban_state(False)

            CLinkText:
                text: "Refresh"

            CLinkIcon:
                icon: "restart"
